### ISSUE TITLE
Woo Comerce

### ISSUE THREAD

**Issue by ratatuille** [monirulalom/woocommerce-hints-for-brackets#1]
Hello there could tell us or show us how Wooo e-comerce work please?

**Comment by monirulalom** [comment]
Please visit the [wiki](https://github.com/monirulalom/woocommerce-hints-for-brackets/wiki/) to see how this extension works.
- [Installation](https://github.com/monirulalom/woocommerce-hints-for-brackets/wiki/Installation)
- [Writting your code](https://github.com/monirulalom/woocommerce-hints-for-brackets/wiki/Writting-your-code)

Feel free to ask if you have any more questions.
